development:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: spree_db_test1
  pool: 5
  username: postgres
  password: postgres

# test:
#   adapter: postgresql
#   encoding: unicode
#   host: localhost
#   database: shopqi_test
#   pool: 5
#   username: postgres
#   password: postgres

production:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: spree_db_test2
  pool: 5
  username: postgres
  password: postgres 
